name: Deploy na S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}

      - name: Copy files to S3_A
        run: |
          aws s3 sync "README.md" s3://${{ secrets.BUCKET_NAME_A }} --delete --exclude ".git/*" --exclude ".github/*"

      - name: Copy files to S3_B
        run: |
          aws s3 sync "README.md" s3://${{ secrets.BUCKET_NAME_B }} --delete --exclude ".git/*" --exclude ".github/*"

      - name: Copy files to S3_C
        run: |
          aws s3 sync "README.md" s3://${{ secrets.BUCKET_NAME_C }} --delete --exclude ".git/*" --exclude ".github/*"

      - name: Invalidate Cache CDN A
        run: |
          aws cloudfront creat-invalidation --distribution-id ${{ secrets.CDN_ID_A }} --paths "/*"

      - name: Invalidate Cache CDN B
        run: |
          aws cloudfront creat-invalidation --distribution-id ${{ secrets.CDN_ID_B }} --paths "/*"

      - name: Invalidate Cache CDN C
        run: |
          aws cloudfront creat-invalidation --distribution-id ${{ secrets.CDN_ID_C }} --paths "/*"
